### PR TITLE
Create foreign key in failed_payment

### LINKED ISSUE #223: Create foreign key for FailedPayment
Should `stripe_customer_id` be a foreign key?

https://github.com/GeekZoneHQ/web/blob/4674d00bd634207dcf0f40512f7941494a2adbb6/memberships/models.py#L138-L141

Must the user be a member to make a payment?
If not, what would happen when a failed payment gets logged and there is no member for that `stripe_customer_id`?

### PR DESCRIPTION
**Pull request by SamWinterhalder**
There should be a foreign key in `failed_payment` so that any failed payments for a member can easily be found.

It will also help with GDPR art. 17.

Fixes #223

### CODE REVIEW

**Comment by SamWinterhalder** [comment]
I would like to point out that I am still getting [WinError 10053] quite when using Firefox.

I have no way of telling how much of this is Windows/my network config being silly or if there is an actual issue that needs to be addressed with Firefox. If this is fine on other Windows machines then I am happy to continue using Chrome, where it seems to be working more reliably.

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 65484)
Traceback (most recent call last):
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__     
    self.handle()
  File "C:\Users\Sam\OneDrive\Documents\GitHub Repositories\web\venv\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "C:\Users\Sam\OneDrive\Documents\GitHub Repositories\web\venv\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host 
machine
----------------------------------------
```

**Comment by SamWinterhalder** [comment]
@jamesgeddes I am happy 👍

**Comment by jamesgeddes** [comment]
Loom a demo?

**Comment by SamWinterhalder** [comment]
> Loom a demo?

Nothing much to show - it doesn't throw the errors on Ubuntu. I can record the console if you like?!

As for the actual functionality of the PR - it just changes what is stored in the database

**Comment by SamWinterhalder** [comment]
Fixes #223

**Review by jamesgeddes — APPROVED** [review]

**Pull request merged**
