### PR TITLE
Help text improvements

### LINKED ISSUE #104: helptext to info buttons
Tidy `helptext` into info buttons

`<span class="helptext">`

Ensure that the solution is still accessible for screen readers.

### PR DESCRIPTION
**Pull request by tbentham**
Changes:
* Redesigned help text popover, e.g. replaced arrow with SVG, moved popover to appear above source element.
* Adapted for mobile screens - narrowed max width and added JS code to stop text appearing off the righthand side of the screen.
* Set help text on register form to appear when input field is focused (only for non-checkbox fields).
* Moved help text code to a reusable template at `inc/help_text.html`.

I'm happy to leave this now until launch (unless someone spots an issue).

Resolves #104.

### CODE REVIEW

**Review by Freshrojek — COMMENTED** [review]
Looks good! 
There's a lot to tick between each email/phone/post having both updates and notification so just wondering if it could be put into and 'Receive updates' heading with  email, post and phone updates underneath and then a 'notifications' heading with the other three underneath. The help text could then be on the headings? Just an idea that you might have already considered though lol.
Otherwise the help text looks nice!

**Comment by Freshrojek** [comment]
and SMS*

**Comment by tbentham** [comment]
That sounds like a good idea! I'll see if I can do that when I'm working on form styling this week (otherwise something for post-go-live).

**Comment by Freshrojek** [comment]
Cool, definitely not a must-have

**Review by Freshrojek — APPROVED** [review]

**Comment by Freshrojek** [comment]
And it may not even look nice so guess just experimenting after the pre-go live stuff is done

**Pull request merged**
