### PR TITLE
setup & run script

### LINKED ISSUE #220: setup.sh
Create a shell script that installs all requirements.

### Impact

Low

### Urgency

Later

### PR DESCRIPTION
**Pull request by jamesgeddes**
* Created `run.sh` as I have designed it to run installations + servers on the first run and then just the servers on the second run
* updated `readme.md` to reflect
* added `.setup_done` to `.gitignore`

resolves #220

### CODE REVIEW

**Comment by tbentham** [comment]
Happy to test this out on my Windows machine if needed - just say the word. :)

**Comment by jamesgeddes** [comment]
@tbentham yes, please! It should be ready to test now, please do give it a go at your earliest convenience

**Comment by jamesgeddes** [comment]
could include [stripe-cli](https://stripe.com/docs/stripe-cli)

**Comment by tbentham** [comment]
Tried running on WSL - `run.sh` exited after the Python3 installation, then I executed the rest manually with `sudo` preceding each command.

Managed to get it working, though a few comments:

- `python3 manage.py tailwind install` needs to be run in the virtual environment apparently, so after `. env/bin/activate`.
- The `gnome-terminal` command didn't work, even after I installed it. I used `&` after each command and that seemed to work just fine.
- I notice the script only runs `. env/bin/activate` in the initial setup, though it needs to be run every time -  also, might be worth running `pip3 install -r requirements.txt` every time too, as the file seems to be updated regularly.
- Not completely sure if Tailwind is working. Probably just me, as I'm not sure how to link the stylings in the 'theme' app to the HTML files in the 'memberships' app.

**Pull request closed without merging**
