### PR TITLE
Feature 329

### PR DESCRIPTION
**Pull request by giulio-giunta**
Here is the implementation of a full ci/cd pipeline that builds and deploys only from master branch.

### CODE REVIEW

**Comment by jamesgeddes** [comment]
@giulio-giunta Could you add the linked issues please? ty muchly 😄

**Review by jamesgeddes — DISMISSED** [review]

**Review by jamesgeddes — DISMISSED** [review]

**Comment by giulio-giunta** [comment]
@jamesgeddes In this case the pipeline didn't run because as configured in the circleci config file it only runs from `master` branch. Since this PR is raised from `feature-329` branch it will never run, so the `main` required check will be never carried out. In this case we need to skip this check, as we don't want this pipeline to run from any branch other than `master`. As soon as we merge this PR, a circleci pipeline will be kicked from master

**Comment by jamesgeddes** [comment]
@giulio-giunta is that why CircleCI appears to be hanging?

**Comment by giulio-giunta** [comment]
Yes, that's the reason!

**Comment by jamesgeddes** [comment]
Need to add something that builds in branches too then else we will be stuck in a loop

**Comment by giulio-giunta** [comment]
Hi James,

You are right, I just did that so now the pipeline builds from master and
any feature branch, but currently only deploys from master.

Giulio

**Comment by jamesgeddes** [comment]
Looks like the `main` job is still hung but the `build-test-deploy` job has succeeded. Odd.

**Comment by giulio-giunta** [comment]
@jamesgeddes Yes, that's exactly what I don't get. I changed the name of the workflow from "main" to "build-test-deploy". Do you know how to configure the checks in Github? Maybe if we remove the "main" check, will be able to move on

**Comment by giulio-giunta** [comment]
@jamesgeddes all checks have passed, but the PR needs one more reviewer.

**Review by jamesgeddes — APPROVED** [review]

**Comment by jamesgeddes** [comment]
Remember that we need #432 at some point soon 😄

**Review by Freshrojek — COMMENTED** [review]
Looks good :)

**Comment by Freshrojek** [comment]
@giulio-giunta would you like me to delete the branch?

**Comment by giulio-giunta** [comment]
Oh sorry Jack, I forgot to delete the branch. I'll do that

**Comment by Freshrojek** [comment]
No need to be sorry 😁

**Pull request merged**
