### PR TITLE
Docker config updates

### PR DESCRIPTION
**Pull request by jamesgeddes**
Created on behalf of @giulio-giunta as GitHub would not allow him to do it.

@giulio-giunta Please explain what this PR achieves.

### CODE REVIEW

**Comment by giulio-giunta** [comment]
In this PR there is the configuration for the following:
- postgres integration in settings.py 
- django probes (to check whether the primary database is ready to accept connections) added into installed apps in settings.py 
- addition of django probes and psycopg2 (PostgreSQL database adapter for Python) in requirements.txt
- addition of command to "python3 manage.py migrate" and env_file in docker-compose

**Comment by jamesgeddes** [comment]
@giulio-giunta Please resolve conflicts and tests so that we can get this one merged.

**Comment by giulio-giunta** [comment]
Hey James,

What is it about? I can't find #288.

**Comment by jamesgeddes** [comment]
@giulio-giunta This _is_ #288 :laughing:

**Pull request closed without merging**
