### PR TITLE
Adds x-clacks-overhead header

### LINKED ISSUE #344: Add X-Clacks-Overhead header
https://xclacksoverhead.org/home/about

Would you consider adding the X-Clacks-Overhead header to the site? For the geek value, of course.

### PR DESCRIPTION
**Pull request by jamesgeddes**
## Description

This change adds the [X-Clacks-Overhead header](https://xclacksoverhead.org/home/about). Each request to Geek.Zone will now include the names of those we have lost, so that while they are gone they will never be forgotten. This is non-visual so no screenshot is available.
## Related Issue

resolves #344 
## Motivation and Context

Helps us to remember those who have passed.
## How Has This Been Tested?

Automated test have been run and passed.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jamesgeddes** [comment]
@giulio-giunta Why am I getting this? https://app.circleci.com/pipelines/github/GeekZoneHQ/web/1187/workflows/02fbedbc-5183-4114-be56-8effc78cc8f2/jobs/1361/steps?invite=true#step-104-27

`ModuleNotFoundError: No module named 'django_probes'`

**Comment by giulio-giunta** [comment]
@James Geddes ***@***.***> in my branch the version for django_probes in
requirements.txt is django-probes==1.6.0
I believe that if you revert the version to that value will resolve the
problem

**Comment by jamesgeddes** [comment]
Thanks @giulio-giunta

**Review by giulio-giunta — APPROVED** [review]
Lgtm

**Comment by jamesgeddes** [comment]
@sienkin this one is done ;)

**Pull request merged**
