### PR TITLE
Feature/docker

### PR DESCRIPTION
**Pull request by giulio-giunta**
This fixes the configuration for circleci

### CODE REVIEW

**Review by SamWinterhalder — APPROVED** [review]

**Comment by giulio-giunta** [comment]
Closed and replaced by another pull request as this threw errors when approved

**Comment by giulio-giunta** [comment]
This partly solves issue #329 as circleci triggers the build of a new image, run tests and stores the new image in Docker Hub. Further work is needed to implement canary deployment, automatic test on blue environment and deployment to production infra.

**Comment by SamWinterhalder** [comment]
It is showing the circleci build-and-test as `Expected — Waiting for status to be reported` which blocks me from approving.

**Review by Freshrojek — APPROVED** [review]
Just submit a review to see if it works.

**Review by SamWinterhalder — DISMISSED** [review]

**Review by SamWinterhalder — APPROVED** [review]

**Pull request merged**
