### PR TITLE
Basic conversion to Tailwind styling

### PR DESCRIPTION
**Pull request by tbentham**
Work in progress, but `base.html` is fully converted - other HTML pages still to be done.

Considered removing `styles.css` as this gets generated by Tailwind at runtime, though this would require all devs to install and run Tailwind (which, from my own experience, can get complicated). Decided to leave it in for now.

### CODE REVIEW

**Comment by CarwynNelson** [comment]
I am meaning to review this. It's quite a large pull request so we might want to do some shifting around in git - but I'm also conscious that I don't want git to stop you from getting stuff done.

**Comment by tbentham** [comment]
@jamesgeddes The branch is now up-to-date with `master` and ready to review - I'll hold off on pushing any further changes until then.

Might be easier if I walk through the changes with whoever's reviewing - let me know if you want to do so.

**Comment by tbentham** [comment]
Resolves:
- #106 - form rendering options - now much more customisable.
- #104 - helptext to info - needs fine-tuning, but basically working.

**Review by jamesgeddes — COMMENTED** [review]
Great work Tristan! It would be preferable to rebase commits, are you happy to cherry-pick? There are lots of commits here. Carwyn gave Sam some hints in #201 if that helps.

**Comment by tbentham** [comment]
Never done it before but I'll give it a go.

**Comment by jamesgeddes** [comment]
Give me a shout if you get stuck :smile:

**Comment by tbentham** [comment]
Done! So glad you told me about cherry picking - very satisfying clearing out the bad commits!

**Comment by jamesgeddes** [comment]
Sorry @tbentham, I just added my PR so this is now out of date. Take a look at [A Better Git Workflow with Rebase](https://www.youtube.com/watch?v=f1wnYdLEpgI) as this is what you need to pull the commits forward ahead of the current master, though skip the very last step where he tells you to push from master (because you are not allowed to at GZ) and push from your newly rebased branch.

**Comment by tbentham** [comment]
@jamesgeddes Just did the rebase now - I think I'm getting the hang of it.

**Review by jamesgeddes — APPROVED** [review]

**Comment by jamesgeddes** [comment]
Great job, well done @tbentham

**Comment by tbentham** [comment]
Is there any harm in continuing on the `tailwind-styling` branch, or would it be better to start a new branch?

**Comment by jamesgeddes** [comment]
Start a new branch :smile:

**Comment by jamesgeddes** [comment]
Try and keep branches to just one feature, that way it is easier to merge them in

**Pull request merged**
