### PR TITLE
added the healtcheck ec2 instance in the AWS to check the health and …

### PR DESCRIPTION
**Pull request by kbcbals**
## Description
High availability of the GZ:
Healtcheck instance is spun off in AWS 'us-east-1' region, keeps an eye on the GZ. when the site is down, 
invokes the infra in Azure, to kepp the site running uninterrupted

## Motivation and Context
provide the much needed high availability via multi cloud setup

## How Has This Been Tested?
spun the cluster to check the REST API getting called from to switch

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GeekZoneHQ/contributing)** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by aevivas — APPROVED** [review]
No major observations.  I usually run `terraform fmt` to nicely format terraform configuration files, this is a personal preference though.

**Comment by kbcbals** [comment]
> No major observations. I usually run `terraform fmt` to nicely format terraform configuration files, this is a personal preference though.

Yep. I missed tat. well spotted.

**Comment by giulio-giunta** [comment]
I think the terraform folder should be placed in the infra repo along with all the other terraform files. Not sure whether we need to create the ec2 instance to monitor the cluster health for every PR that is raised. I think this should be one off when we launch and should be kicked from main.

**Comment by kbcbals** [comment]
> I think the terraform folder should be placed in the infra repo along with all the other terraform files. Not sure whether we need to create the ec2 instance to monitor the cluster health for every PR that is raised. I think this should be one off when we launch and should be kicked from main.

Makes sense to me as well.  It's a one time activity when the cluster is spun, infra seems to be the place. Will move it.

**Comment by Freshrojek** [comment]
Hi @kbcbals 👋🏼 
Let me know once it's been moved and you're happy for me to close the PR :)

**Pull request closed without merging**
