### PR TITLE
web-685 update eisenhower action to include trigger issue

### LINKED ISSUE #685: Update Eisenhower action to include required trigger issue
### What did you expect?

Trigger issue must be passed to Eisenhower github action

### What actually happened?

Trigger issue not currently passed to Eisenhower action

### Impact

High

### Urgency

Now

### What browsers are you seeing the problem on?

_No response_

### What operating system are you using?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jamesgeddes**
## Description

The Eisenhower prioritisation issue now requires the triggering issue to be passed in. This provides that.

Only real change is the addition of

`GH_ISSUE_NUMBER: ${{ github.event.issue.number }}`

## Related Issue

resolves #685 
## Motivation and Context

Makes the action more efficient by only processing the trigger issue. Should prevent us from hitting rate limits.
## How Has This Been Tested?

Existing logic not changed, only updates the issues that it processes.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GeekZoneHQ/contributing)** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jamesgeddes** [comment]
@giulio-giunta Ticket prioritization is currently broken without this. May I request your review, please?

**Review by giulio-giunta — APPROVED** [review]
Once you either rebase or merge "main", the Snyk check will pass successfully. It's failing now because the "certifi" dependency in requirements.txt in your branch needs to be updated, but this was already done in "main".

**Comment by giulio-giunta** [comment]
@jamesgeddes,
It actually failed again, I need to look into this.

**Review by giulio-giunta — APPROVED** [review]
All the checks have passed successfully.

**Comment by giulio-giunta** [comment]
@jamesgeddes, 
This can now be merged. It needed updating the Snyk Github action, along with the version of a couple of dependencies.

**Pull request merged**
