### PR TITLE
Run tailwind from the app docker container

### LINKED ISSUE #456: Run Tailwind CSS in Docker
### What's your idea?

Create a set-up for running Tailwind CSS in a Docker container

A work currently in progress, based on [tristanstraub/docker-tailwindcss](https://github.com/tristanstraub/docker-tailwindcss).

### Impact

Low

### Urgency

Now

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by giulio-giunta**
This resolves #456

It allows running tailwind commands from the app container by adding nodejs and npm. 
Since this feature is useful only to those working with the frontend code, a Dockerfile (in the docker/frontend/ folder) and docker-compose.frontend.yml file have been added to avoid interference with the existing Dockerfile and docker-compose.yml files (used for ci/cd). 
Tailwind commands can only be run as the root user, as this needs the necessary preveleges to write from the container to the project folder (see the volume created in the docker-compose.frontend.yml)

Running tailwind commands from the app container is not crucial, but is very useful for development as docker has proven to be easier and quicker than local virtual environments.

## How Has This Been Tested?
I verified this work by running the following commands from the project folder:
`docker-compose -f docker-compose.frontend.yml run web sh` 
`python3 manage.py tailwind install`
`python3 manage.py tailwind start`
`python3 manage.py tailwind build`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GeekZoneHQ/web/blob/master/CONTRIBUTING.md)** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jamesgeddes — APPROVED** [review]

**Comment by jamesgeddes** [comment]
@giulio-giunta Is superlinter looking for our version file?

**Comment by jamesgeddes** [comment]
@tbentham have your reviewed this?

**Comment by jamesgeddes** [comment]
@giulio-giunta I have approved this but would like @tbentham to take a look too as it's mainly front end that will need this.

**Comment by giulio-giunta** [comment]
I agree, let's wait for Tristan to take a look at this PR

**Comment by giulio-giunta** [comment]
@James Geddes ***@***.***> I don't really know

**Comment by tbentham** [comment]
I've tried running it on Windows and it seems to work fine - the only issue I'm having is that `tailwind start` doesn't detect changes automatically as it should, meaning you have to re-run the `tailwind start` command to update `styles.css`. Thankfully, this is only an issue when editing base styles in the `theme` directory, which does not happen often. However, if we decide to use Tailwind's "just-in-time" mode in future, this would become a big inconvenience.

It's a minor issue for now anyway. I'm happy to approve this since it does the essential thing of running Tailwind in Docker. Thanks for all your work on this @giulio-giunta.

**Review by tbentham — APPROVED** [review]

**Comment by giulio-giunta** [comment]
Fixed superlinter check issue by modifying line 22 in .github/workflows/superlinter.yml from `uses: github/super-linter@v3` to `uses: github/super-linter@v3.17.0` (in the previous failed check the superlinter image used was v3.17.1).
[Here](https://github.com/github/super-linter/issues/2255) is the explanation of the workaround

**Comment by giulio-giunta** [comment]
@jamesgeddes could you reapprove this PR, please?

**Comment by jamesgeddes** [comment]
Will take another look in the morning 🙂

**Review by jamesgeddes — APPROVED** [review]

**Pull request merged**
