### PR TITLE
Retention policy

### LINKED ISSUE #77: Check if payment complete
Requires #39 

When a member has logged in, check if their membership fee is due and if that payment has completed.

### PR DESCRIPTION
**Pull request by SamWinterhalder**
Check if a Sand membership fee is due on each member.

- [x] send an email upon failed payment

If Sand membership fee not yet paid (new member):
 - [x] force payment process on  login
 - [x] send a reminder email after 24 hours
 - [x] send a reminder email after 72 hours
 - [x] ~~delete account and~~ send email to notify after 120 hours.

Fixes #77 

(Following is no longer PGL)
~~If Sand membership fee is due soon, send member reminders to pay.~~ Relates to #128 

~~If Sand membership fee is not paid after six months:~~
 - ~~update their membership termination date~~
 - ~~the author on posts published by that member must be changed to "Anonymous [animal]"~~
 - ~~their member profile must be set to private.~~

### CODE REVIEW

**Comment by SamWinterhalder** [comment]
@jamesgeddes I have just started thinking about/implementing the first remind email and it would not work to send all the emails at 9am every day for all users who do not have the `has_paid_sand` permission. This perm is granted afer successful payment and that could be a few minutes after the member has registered.

A common scenario would be if a member registers at 08:59, starts their payment but when they finish it is already 09:01. This would mean that the user does not have the `has_paid_sand` perm as their payment has not technically gone through, but it is not because it has failed.

For this reason I am starting to reconsider the 'only having `has_paid_sand` permission' but am not yet sure about what to do.
I think one way to do it (whilst keeping only the one permission) is to look at the datetime of when the user signed up to see if it has only been a few minutes or if their payment is taking some time.

**Comment by jamesgeddes** [comment]
That's a fair point. Perhaps we should go with the 24 hours after the individual registers.

**Comment by SamWinterhalder** [comment]
@jamesgeddes I think [celery beat](https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html) is the best option for scheduling the recurring task of sending the emails.

**Comment by SamWinterhalder** [comment]
Another option is to schedule a **check**, upon membership creation, to find if the member has paid, if they still have not, send an email and schedule the next **check**. This would be easier than using celery-beat and creating periodic tasks which checks through all members.

**Comment by SamWinterhalder** [comment]
NOTE: When running celery, `--pool=solo` is a necessary command line arguement for Windows. (have not yet tested on Linux).
Relates to #246

**Comment by SamWinterhalder** [comment]
NOTE FOR WINDOWS: There needs to be another worker process/thread available to call a task from within another task. This may cause issues when running on Windows as the only way I could get my version to work was by limitting workers using `--pool=solo`.

**Comment by SamWinterhalder** [comment]
@jamesgeddes Please can we either meet up at some point or can I have a list of exactly what needs to be done on member deletion (to comply with GDPR, to keep payments anonymous, etc)?

**Comment by jamesgeddes** [comment]
@SamWinterhalder I am free in an hour, let's jump into the GZ dev channel at 1730

**Comment by jamesgeddes** [comment]
I will take a look at the CircleCI config to ensure that it is pulling in the correct env

**Comment by jamesgeddes** [comment]
logged #271

**Comment by SamWinterhalder** [comment]
I am not sure the best conditions to use, to determine whether to force the member into payment.

One scenario already mentioned is a payment that might take an hour, this will not be payed but the user has done all they can so it might be incorrect to just use whether they have paid or not.

**Comment by jamesgeddes** [comment]
Do we get a "payment processing" from stripe?

**Comment by SamWinterhalder** [comment]
Should do, I am not sure how I am going to be able to differentiate between Sand payment and any other payments for `stripe_customer_id`. Need to find a way of making sure I am looking at the correct payment but shall look into this later today or Saturday.

**Comment by SamWinterhalder** [comment]
I think that instead of making more requests than we need to, we can store the most recent event of the payment in the database (not every event but the significant ones that will help with knowing what is happening with the members payment).

**Comment by Freshrojek** [comment]
The CircleCI error is stating that nothing has been written to the console in 10 mins so it timed out. [Check here](https://stackoverflow.com/questions/56176716/how-to-resolve-circleci-automated-job-hangs-fails-parcel-build-with-css-import).

**Comment by SamWinterhalder** [comment]
> The CircleCI error is stating that nothing has been written to the console in 10 mins so it timed out. [Check here](https://stackoverflow.com/questions/56176716/how-to-resolve-circleci-automated-job-hangs-fails-parcel-build-with-css-import).

I think this is because we do not have Celery or RabbitMQ installed on ther CircleCI instance. (I have got @jamesgeddes working on this 😄)

**Comment by jamesgeddes** [comment]
It does occur to me that we don't actually have any tests that ask circle ci to run anything in rabbit. I'm not saying that we should not have the right testing environment but that does seem kind of odd.

**Comment by SamWinterhalder** [comment]
> It does occur to me that we don't actually have any tests that ask circle ci to run anything in rabbit. I'm not saying that we should not have the right testing environment but that does seem kind of odd.

I think we need circlieci to be able to know what rabbitmq is first 😄

**Comment by Freshrojek** [comment]
when running manage.py test I get an assertion error in `test_stripe_webhooks.py` on line 122 "self.assertEqual(1, payments.count())" where is says 1!=0, and CircleCi says that manage.py test is what's causing an issue so could be something to do with that?

**Comment by Freshrojek** [comment]
and when changing 1 to 0 the test works

**Comment by SamWinterhalder** [comment]
> when running manage.py test I get an assertion error in `test_stripe_webhooks.py` on line 122 "self.assertEqual(1, payments.count())" where is says 1!=0, and CircleCi says that manage.py test is

Yeh it is not behaving, I have somehow broken something to do with Stripe somewhere becuase I keep getting `500`'s back from every Stripe event.

**Comment by Freshrojek** [comment]
sounds promising!

**Comment by SamWinterhalder** [comment]
Fixes #271

**Comment by jamesgeddes** [comment]
@SamWinterhalder convert this and add me as a reviewer so I can approve :smile:

**Review by jamesgeddes — APPROVED** [review]
Great job 👍

**Comment by Freshrojek** [comment]
Well done, big effort!

**Pull request merged**
